"""Updated transaction table

Revision ID: d3f35b61d9e6
Revises: 3a1aefa020ab
Create Date: 2026-09-20 16:30:57.447394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f35b61d9e6'
down_revision: Union[str, Sequence[str], None] = '3a1aefa020ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('transactions', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'transaction_at')
    # ### end Alembic commands ###
